"""initial schema

Revision ID: 198c6ee2994b
Revises: 
Create Date: 2026-07-10 12:13:33.149066

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '198c6ee2994b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('equity_curve_json', sa.Text(), nullable=True),
    sa.Column('benchmark_curve_json', sa.Text(), nullable=True),
    sa.Column('drawdown_curve_json', sa.Text(), nullable=True),
    sa.Column('trades_json', sa.Text(), nullable=True),
    sa.Column('monthly_returns_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_ticker'), 'backtest_runs', ['ticker'], unique=False)
    op.create_index('ix_backtest_runs_ticker_created', 'backtest_runs', ['ticker', 'created_at'], unique=False)
    op.create_table('cache_entries',
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('detected_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('matched_keywords', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_events_ticker'), 'detected_events', ['ticker'], unique=False)
    op.create_index('ix_events_ticker_detected', 'detected_events', ['ticker', 'detected_at'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_ticker'), 'instruments', ['ticker'], unique=True)
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=40), nullable=False),
    sa.Column('train_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('train_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('n_train_samples', sa.Integer(), nullable=False),
    sa.Column('n_test_samples', sa.Integer(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('baseline_metrics_json', sa.Text(), nullable=False),
    sa.Column('feature_names_json', sa.Text(), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_ticker'), 'model_runs', ['ticker'], unique=False)
    op.create_index('ix_model_runs_ticker_trained', 'model_runs', ['ticker', 'trained_at'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_status', sa.String(length=16), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_ticker'), 'news_articles', ['ticker'], unique=False)
    op.create_index(op.f('ix_news_articles_url_hash'), 'news_articles', ['url_hash'], unique=True)
    op.create_index('ix_news_ticker_published', 'news_articles', ['ticker', 'published_at'], unique=False)
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('data_status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_bars_ticker'), 'price_bars', ['ticker'], unique=False)
    op.create_index('ix_price_bars_ticker_interval_ts', 'price_bars', ['ticker', 'interval', 'ts'], unique=True)
    op.create_table('provider_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_health_provider_name'), 'provider_health', ['provider_name'], unique=True)
    op.create_table('sentiment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('text_excerpt', sa.Text(), nullable=False),
    sa.Column('compound', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=40), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_scores_ticker'), 'sentiment_scores', ['ticker'], unique=False)
    op.create_index('ix_sentiment_ticker_scored', 'sentiment_scores', ['ticker', 'scored_at'], unique=False)
    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_external_id'), 'social_posts', ['external_id'], unique=True)
    op.create_index(op.f('ix_social_posts_ticker'), 'social_posts', ['ticker'], unique=False)
    op.create_index('ix_social_ticker_created', 'social_posts', ['ticker', 'created_at'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_owner_key'), 'watchlists', ['owner_key'], unique=True)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('as_of_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_direction', sa.String(length=8), nullable=False),
    sa.Column('probability_up', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.String(length=16), nullable=False),
    sa.Column('top_features_json', sa.Text(), nullable=False),
    sa.Column('sentiment_shift_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_ticker'), 'predictions', ['ticker'], unique=False)
    op.create_index('ix_predictions_ticker_asof', 'predictions', ['ticker', 'as_of_date'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('change_abs', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('market_status', sa.String(length=20), nullable=True),
    sa.Column('data_status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_ticker'), 'price_snapshots', ['ticker'], unique=False)
    op.create_index('ix_price_snapshots_ticker_asof', 'price_snapshots', ['ticker', 'as_of'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchlist_items_unique', 'watchlist_items', ['watchlist_id', 'ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watchlist_items_unique', table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index('ix_price_snapshots_ticker_asof', table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_ticker'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index('ix_predictions_ticker_asof', table_name='predictions')
    op.drop_index(op.f('ix_predictions_ticker'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_watchlists_owner_key'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index('ix_social_ticker_created', table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_ticker'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_external_id'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index('ix_sentiment_ticker_scored', table_name='sentiment_scores')
    op.drop_index(op.f('ix_sentiment_scores_ticker'), table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index(op.f('ix_provider_health_provider_name'), table_name='provider_health')
    op.drop_table('provider_health')
    op.drop_index('ix_price_bars_ticker_interval_ts', table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_ticker'), table_name='price_bars')
    op.drop_table('price_bars')
    op.drop_index('ix_news_ticker_published', table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_url_hash'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_ticker'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index('ix_model_runs_ticker_trained', table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_ticker'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_instruments_ticker'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index('ix_events_ticker_detected', table_name='detected_events')
    op.drop_index(op.f('ix_detected_events_ticker'), table_name='detected_events')
    op.drop_table('detected_events')
    op.drop_table('cache_entries')
    op.drop_index('ix_backtest_runs_ticker_created', table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_ticker'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
